env:
    node: true
    jest: true
    es6: true
    browser: true

extends:
    - airbnb-base
    - prettier

parserOptions:
    ecmaVersion: latest

rules:
    import/extensions: 0
    no-console: off
    indent: ['error', 4]
    no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
